# Kustomize Strategic Merge Patch - partial spec is intentional
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  template:
    spec:
      containers:
        - name: search-service
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
