# Preview service for Catalog Service Blue-Green deployment
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-preview
  namespace: flix
  labels:
    app: catalog-service
    service-type: preview
spec:
  selector:
    app: catalog-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
  type: ClusterIP
