# Argo Rollout for Frontend with Blue-Green strategy
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: flix
  labels:
    app: frontend
    component: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: frontend
        environment: bluegreen
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: frontend
          image: tegar900/flixstream-frontend:latest
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: bluegreen-frontend-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
  strategy:
    blueGreen:
      activeService: bluegreen-frontend
      previewService: bluegreen-frontend-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60
