# Preview service for Frontend Blue-Green deployment
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  namespace: flix
  labels:
    app: frontend
    service-type: preview
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
