# Preview service for Payment Service Blue-Green deployment
apiVersion: v1
kind: Service
metadata:
  name: payment-service-preview
  namespace: flix
  labels:
    app: payment-service
    service-type: preview
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 3005
      targetPort: 3005
      protocol: TCP
  type: ClusterIP
