# Preview service for Recommendation Service Blue-Green deployment
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-preview
  namespace: flix
  labels:
    app: recommendation-service
    service-type: preview
spec:
  selector:
    app: recommendation-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
  type: ClusterIP
