# Argo Rollout for Search Service with Blue-Green strategy
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: search-service
  namespace: flix
  labels:
    app: search-service
    component: backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
        component: backend
        environment: bluegreen
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: search-service
          image: tegar900/flixstream-search-service:latest
          ports:
            - containerPort: 3004
              name: http
          envFrom:
            - configMapRef:
                name: bluegreen-search-service-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
  strategy:
    blueGreen:
      activeService: bluegreen-search-service
      previewService: bluegreen-search-service-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60
