apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flixstream-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tegar97/flixstream-ops.git
    targetRevision: main
    path: argocd/environments
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
