# PodDisruptionBudget for api-gateway
# Ensures at least 1 pod is always available during voluntary disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: flix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
