# PodDisruptionBudget for catalog-service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-service-pdb
  namespace: flix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: catalog-service
