# PodDisruptionBudget for payment-service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  namespace: flix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-service
