# PodDisruptionBudget for recommendation-service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recommendation-service-pdb
  namespace: flix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: recommendation-service
