# PodDisruptionBudget for search-service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: search-service-pdb
  namespace: flix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: search-service
