# PodDisruptionBudget for user-service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-service-pdb
  namespace: flix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: user-service
