apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-gateway
  namespace: flix
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: backend
        environment: prod
    spec:
      containers:
        - name: api-gateway
          image: tegar900/flixstream-api-gateway:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: prod-api-gateway-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    blueGreen:
      activeService: prod-api-gateway
      previewService: prod-api-gateway-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
