apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog-service
  namespace: flix
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
        component: backend
        environment: prod
    spec:
      containers:
        - name: catalog-service
          image: tegar900/flixstream-catalog-service:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: prod-catalog-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    blueGreen:
      activeService: prod-catalog-service
      previewService: prod-catalog-service-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
