apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: flix
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: frontend
        environment: prod
    spec:
      containers:
        - name: frontend
          image: tegar900/flixstream-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: prod-frontend-config
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    blueGreen:
      activeService: prod-frontend
      previewService: prod-frontend-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
