apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-preview
  namespace: flix
spec:
  selector:
    app: recommendation-service
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
