apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service
  namespace: flix
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        component: backend
        environment: prod
    spec:
      containers:
        - name: user-service
          image: tegar900/flixstream-user-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: prod-user-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    blueGreen:
      activeService: prod-user-service
      previewService: prod-user-service-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
